using System;
using System.Collections.Generic;
using TopSpeed.Server.Protocol;

namespace TopSpeed.Server.Tracks
{
    internal static class TrackCatalog
    {
        private static MultiplayerDefinition Def(TrackType type, TrackSurface surface, TrackNoise noise, int length)
        {
            return new MultiplayerDefinition
            {
                Type = (byte)type,
                Surface = (byte)surface,
                Noise = (byte)noise,
                Length = (uint)length
            };
        }

        private static readonly MultiplayerDefinition[] TrAmerica =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 80000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000)
        };

        private static readonly MultiplayerDefinition[] TrAustria =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HairpinLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000)
        };

        private static readonly MultiplayerDefinition[] TrBelgium =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 7000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 10000)
        };

        private static readonly MultiplayerDefinition[] TrBrazil =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrChina =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000)
        };

        private static readonly MultiplayerDefinition[] TrEngland =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 28000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrFinland =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.HairpinLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrFrance =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrGermany =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000)
        };

        private static readonly MultiplayerDefinition[] TrIreland =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 70000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 10000)
        };

        private static readonly MultiplayerDefinition[] TrItaly =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 70000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrNetherlands =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 6000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 18000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 18000)
        };

        private static readonly MultiplayerDefinition[] TrPortugal =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000)
        };

        private static readonly MultiplayerDefinition[] TrRussia =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000)
        };

        private static readonly MultiplayerDefinition[] TrSpain =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 70000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000)
        };

        private static readonly MultiplayerDefinition[] TrSweden =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000)
        };

        private static readonly MultiplayerDefinition[] TrSwitserland =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 31000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 39000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000)
        };

        private static readonly MultiplayerDefinition[] TrAdvHills =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 25000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 28000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 22000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 19000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 10000),
            Def(TrackType.HardLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Crowd, 40000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 45000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 17500),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 9500),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 9000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 10000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 6000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 11000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Crowd, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 20000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Crowd, 40000)
        };

        private static readonly MultiplayerDefinition[] TrAdvCoast =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Ocean, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.Ocean, 25000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Ocean, 30000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Ocean, 19000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 25000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 38000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 19000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 19000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 22000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Ocean, 21000),
            Def(TrackType.Left, TrackSurface.Sand, TrackNoise.Ocean, 19000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.Ocean, 20000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Ocean, 57000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.Ocean, 19000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 16000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 22000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Ocean, 35000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 22000),
            Def(TrackType.Left, TrackSurface.Sand, TrackNoise.NoNoise, 21000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 13000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Ocean, 32000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 19000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 12000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 19000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 19000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 14000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Water, TrackNoise.Ocean, 60000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 15000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 42000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Ocean, 50000)
        };

        private static readonly MultiplayerDefinition[] TrAdvCountry =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 35000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 35000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.River, 61000),
            Def(TrackType.HardLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 25000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Water, TrackNoise.Thunder, 31000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 28000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 21000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 35000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 16000),
            Def(TrackType.Straight, TrackSurface.Water, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 27000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 22000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 28000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 13000),
            Def(TrackType.HairpinRight, TrackSurface.Gravel, TrackNoise.River, 21000),
            Def(TrackType.Straight, TrackSurface.Water, TrackNoise.River, 48000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 15000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.NoNoise, 12000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Thunder, 12000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 32000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 18000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 24000),
            Def(TrackType.EasyRight, TrackSurface.Water, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 14000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 12000),
            Def(TrackType.HairpinLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 35000),
            Def(TrackType.Right, TrackSurface.Gravel, TrackNoise.Thunder, 21000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.River, 70000)
        };

        private static readonly MultiplayerDefinition[] TrAirport =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 22000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 26000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 16000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 23000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 26000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 28000),
            Def(TrackType.EasyRight, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Runway, 6000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 46000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 21000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 18000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 16000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 27000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 16000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 12000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 28000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 27000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Jet, 6000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 36000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 19000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 11000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 7000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.Helicopter, 13000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 18000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 6000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 12000),
            Def(TrackType.HairpinRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 11000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 17000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 21000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Jet, 6000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 24000),
            Def(TrackType.EasyLeft, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Left, TrackSurface.Gravel, TrackNoise.NoNoise, 17000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 21000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 16000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 12000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Helicopter, 30000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 16000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 40000)
        };

        private static readonly MultiplayerDefinition[] TrDesert =
        {
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Crowd, 150000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 20000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 90000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 100000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.Owl, 20000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 19000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 11111),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 9000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 70000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 8000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.Owl, 10000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 80000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 75000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 125000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 18000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Jet, 5000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 46000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.Owl, 12345),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 10000),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 77777),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 54321),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 99999),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.Owl, 6000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.NoNoise, 10000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 200000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 60000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 35000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 80000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Owl, 8500),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 46000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 60000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 25000),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 42000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 90000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 95000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 500000),
            Def(TrackType.EasyRight, TrackSurface.Sand, TrackNoise.Owl, 6000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 6000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 6000),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 250000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.Owl, 5000),
            Def(TrackType.Left, TrackSurface.Sand, TrackNoise.NoNoise, 5000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 5000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 15000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.Owl, 7500),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 100000),
            Def(TrackType.HairpinLeft, TrackSurface.Sand, TrackNoise.NoNoise, 75000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 40000),
            Def(TrackType.EasyLeft, TrackSurface.Sand, TrackNoise.NoNoise, 10000),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 60000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.Owl, 10000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 35000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 5000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 44444),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 55555),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 33333),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Owl, 22222),
            Def(TrackType.HairpinRight, TrackSurface.Sand, TrackNoise.NoNoise, 100000),
            Def(TrackType.HardRight, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Sand, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Sand, TrackNoise.NoNoise, 66666),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 666666),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.Owl, 10000),
            Def(TrackType.Straight, TrackSurface.Sand, TrackNoise.NoNoise, 10000)
        };

        private static readonly MultiplayerDefinition[] TrAdvRush =
        {
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 35000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 120000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 53000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.Construction, 70000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 24000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 32000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 19000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 35000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 15000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 52000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 23000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 5000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 25000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 100000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Pile, 85000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.Pile, 32000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 42000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 23000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 21000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 39000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 43000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 38000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 69000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 38000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 43000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 40000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 76000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 100000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 34000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 100000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 20000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 6700),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 82000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 42000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 130000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 23000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 28000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 103000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 34000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 34000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 5000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.Clock, 34000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Clock, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.Clock, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Clock, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 18000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 5000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 120000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Pile, 58000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 62000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 21000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Construction, 40000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Construction, 50000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 100000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 60000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 45000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 52000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 31000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 130000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.Pile, 26000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.Pile, 30000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Pile, 30000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.Pile, 31000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Pile, 30000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Pile, 23000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Pile, 32000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 35000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 43000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 34000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.Clock, 100000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 16000),
            Def(TrackType.HardRight, TrackSurface.Asphalt, TrackNoise.Clock, 100000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.Clock, 80000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 100000),
            Def(TrackType.Left, TrackSurface.Asphalt, TrackNoise.NoNoise, 13000),
            Def(TrackType.HardLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 100000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.Right, TrackSurface.Asphalt, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyRight, TrackSurface.Asphalt, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Asphalt, TrackNoise.NoNoise, 41000),
            Def(TrackType.Straight, TrackSurface.Gravel, TrackNoise.NoNoise, 100000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.NoNoise, 100000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Pile, 70000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Construction, 20000),
            Def(TrackType.Straight, TrackSurface.Asphalt, TrackNoise.Clock, 100000)
        };

        private static readonly MultiplayerDefinition[] TrAdvEscape =
        {
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 38000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 20000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 68000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 6000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 103000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 20000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 130000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 51000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 40000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 5000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 180000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 139000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 25000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 20000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 83500),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 25000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 37000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 58000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 15000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 13000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 5000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 60000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 53000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 38000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 34000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 80500),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 80000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 100000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 90000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 75000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 100000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 18000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 50000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 13000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 60000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 100000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 58000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 100000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 78000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 6000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 32000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 23000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 50000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.NoNoise, 17000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 22000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 30000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 58000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.NoNoise, 10000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 59000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 70000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.Crowd, 52000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.Crowd, 23000),
            Def(TrackType.Left, TrackSurface.Snow, TrackNoise.Crowd, 23000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.Crowd, 37000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.Crowd, 100000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 28000),
            Def(TrackType.EasyLeft, TrackSurface.Snow, TrackNoise.NoNoise, 9200),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.NoNoise, 82000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.NoNoise, 35000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.River, 52000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.River, 30000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.River, 30000),
            Def(TrackType.EasyRight, TrackSurface.Snow, TrackNoise.River, 35000),
            Def(TrackType.Straight, TrackSurface.Snow, TrackNoise.River, 20000),
            Def(TrackType.Right, TrackSurface.Snow, TrackNoise.River, 47000),
            Def(TrackType.Straight, TrackSurface.Water, TrackNoise.River, 85000)
        };

        public static IReadOnlyDictionary<string, TrackData> BuiltIn => BuiltInMap.Value;

        private static readonly Lazy<IReadOnlyDictionary<string, TrackData>> BuiltInMap =
            new Lazy<IReadOnlyDictionary<string, TrackData>>(() => new Dictionary<string, TrackData>(StringComparer.Ordinal)
            {
            ["america"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrAmerica),
            ["austria"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrAustria),
            ["belgium"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrBelgium),
            ["brazil"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrBrazil),
            ["china"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrChina),
            ["england"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrEngland),
            ["finland"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrFinland),
            ["france"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrFrance),
            ["germany"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrGermany),
            ["ireland"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrIreland),
            ["italy"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrItaly),
            ["netherlands"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrNetherlands),
            ["portugal"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrPortugal),
            ["russia"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrRussia),
            ["spain"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrSpain),
            ["sweden"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrSweden),
            ["switserland"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrSwitserland),
            ["advHills"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrAdvHills),
            ["advCoast"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrAdvCoast),
            ["advCountry"] = new TrackData(false, TrackWeather.Rain, TrackAmbience.NoAmbience, TrAdvCountry),
            ["advAirport"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.Airport, TrAirport),
            ["advDesert"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.Desert, TrDesert),
            ["advRush"] = new TrackData(false, TrackWeather.Sunny, TrackAmbience.NoAmbience, TrAdvRush),
            ["advEscape"] = new TrackData(false, TrackWeather.Wind, TrackAmbience.NoAmbience, TrAdvEscape)
            });

    }
}
